server:
  port: 8083  #配置端口号



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

